services:
  - type: web
    name: carambar-api
    env: node
    plan: free
    buildCommand: npm install && npx sequelize-cli db:migrate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production